version: '3.8'
services:
  localstack:
    image: localstack/localstack:3.0.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_CBOR_DISABLE=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.localstack:/etc/localstack/init/ready.d"  # ready hook